name: TeslaQc
favicon: null
layout_spectrum: 0.00098
typography_spectrum: 0.74658
title: Tesla au Québec
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030609'
    - '#4b4f52'
    - '#837c76'
    - '#ced2d1'
    - '#75a4d7'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
